version: "3.8"

services:
  frontend:
    container_name: notulus-frontend
    build:
      dockerfile: ./frontend/Dockerfile
      context: ./
    ports:
      - 8000:8000
    volumes:
      - frontend:/home/user/web
    depends_on:
      - backend

  backend:
    container_name: notulus-backend
    build:
      dockerfile: ./backend/src/main/resources/Dockerfile
      context: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notulus-db
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_DATASOURCE_USERNAME: notulus
      SPRING_DATASOURCE_PASSWORD: notulus
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - 8080:8080
    volumes:
      - backend:/home/user/api
    depends_on:
      - postgres

  redis:
    container_name: notulus-db-cache
    image: redis:latest
    ports:
    - 6379:6379

  postgres:
    container_name: notulus-db
    image: postgres:latest
    environment:
      POSTGRES_USER: notulus
      POSTGRES_PASSWORD: notulus
      POSTGRES_DB: notulus-db
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  frontend:
  backend:
  database:
