server:
  port: 8080
jwt:
  secret: "secret"
spring:
  application:
    name: notulus-backend
  output:
    ansi:
      enabled: always
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/notulus-db
    username: notulus
    password: notulus
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgresSQLDialect
  cache:
    cache-names:
      - notes
    redis:
      time-to-live: 600000
  redis:
    host: localhost
    port: 6379
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
  show-login-endpoint: true
